packages:
  - libs/*
  - plugins/*
  - websites/*

catalog:
  vue: ^3.5.13
  monaco-editor-core: ^0.52.2
  shiki: ^1.26.2
  '@shikijs/transformers': ^1.26.2
  '@shikijs/monaco': ^1.26.2
  sass: 1.86.2
  markdown-it: ^14.1.0
  '@types/markdown-it': ^14.1.2
  markdown-it-container: ^4.0.0
  '@types/markdown-it-container': ^2.0.10
  lodash-es: ^4.17.21
  '@types/lodash-es': ^4.17.12
  type-fest: ^4.31.0

catalogs:
  peer:
    vue: '>=3.5.0'
    monaco-editor-core: '>=0.50.0'
