packages:
  - libs/*
  - plugins/*
  - websites/*

catalog:
  vue: ^3.5.13
  monaco-editor-core: ^0.52.2
  shiki: ^1.26.2
  '@shikijs/transformers': ^1.26.2
  '@shikijs/monaco': ^1.26.2
  sass: 1.86.2

catalogs:
  peer:
    vue: '>=3.5.0'
    monaco-editor-core: '>=0.50.0'
