name: build_playground
timeout: 1200
on:
  push:
    branches:
      - dev
env:
  # 执行前，必须确保 .changeset 目录下有 changeset-playground-xxx.md 变更文件，否则必然出错！！
  project: v_md
  code_repository: v_md
  image_name: vmd_playground
  docker_file: .sahoc/build-playground.Dockerfile
  k8s_cluster_name: sahoc-common-cloud-1
  OUTPUT_BUILD_SUCCESS: false
  OUTPUT_AUTO_VERSION: 0.0.1
  REVISION: master
runs-on: openx_executer_common
jobs:
  执行构建:
    steps:
      - name: 拉取代码
        uses: checkout
        with:
          code_repository: '{{ code_repository }}'
          branch: '{{ REVISION }}'

      - name: 自动生成版本号
        uses: auto_version
        with:
          base_version: vmd

      - name: 打印环境变量
        run: printenv

      - name: 安装依赖
        run: |
          pnpm i

      - name: 构建应用
        env:
          CDN_URL: https://unpkg.openx.huawei.com
          CDN_TYPE: unpkg
        run: |
          pnpm -F @v-md/playground build

      - name: 构建 docker 镜像
        uses: docker_build
        with:
          docker_file: '{{ docker_file }}'
          image_name: '{{ image_name }}'
          image_version: '{{ OUTPUT_AUTO_VERSION }}'

      - name: 上传 docker 镜像
        uses: image_upload
        with:
          image_name: '{{ image_name }}'
          image_version: '{{ OUTPUT_AUTO_VERSION }}'
          project: '{{ project }}'
          code_repository: '{{ code_repository }}'

      - name: 构建成功标记
        run: echo '::set-output name=build_success::true'
  执行部署:
    needs: 执行构建
    when: self.env.OUTPUT_BUILD_SUCCESS == 'true'
    steps:
      - name: 处理 Jinja2 依赖
        run: |
          pip install Jinja2 --break-system-packages
      - name: 部署应用
        uses: k8s_deploy@v2
        with:
          deploy_kind: service
          config_data:
            service_name: '{{ image_name }}'
            load_balancer: ROUND_ROBIN
            instances:
              - name: '{{ image_name }}'
                replicas: 3
                containers:
                  - name: '{{ image_name }}'
                    image: 'sahoc-images.divista.huawei.com:80/k8s-dongguan-1/{{ image_name }}:{{ OUTPUT_AUTO_VERSION }}'
                    resources:
                      limits:
                        cpu: 2000m
                        memory: 1024Mi
                      requests:
                        cpu: 2000m
                        memory: 1024Mi
            routes:
              - domain: vmd.openx.huawei.com
                listen_protocol: https
                target_port: 80
                target_protocol: TCP
                source_path: /v-md/
                destination_path: /
                ca_name: openx_cicd--openx-ssl
                domain_type: external
                type: default
              - domain: vmd.openx.huawei.com
                listen_protocol: http
                target_port: 80
                target_protocol: TCP
                source_path: /v-md/
                destination_path: /
                domain_type: external
                type: default
          project: '{{ project }}'
          k8s_cluster_name: '{{ k8s_cluster_name }}'
